language: c

matrix:
    include:

# native

        - env: test="x64 4.8.4 (make)"
          os: linux
          dist: trusty
          compiler: gcc
          script: make

        - env: test="x64 4.8.4 (autotools)"
          os: linux
          dist: trusty
          compiler: gcc
          script: ./autogen.sh && ./configure CFLAGS="-Werror -Wno-unused-result" && make distcheck

        - env: test="x64 5.0 (autotools)"
          os: linux
          dist: trusty
          compiler: clang
          script: ./autogen.sh && ./configure CFLAGS="-Werror -Wno-unused-result" && make distcheck

        - env: test="x64 4.8.4 (CMake gcc)"
          os: linux
          dist: trusty
          compiler: gcc
          before_script:
              - mkdir gcc_rel && cd gcc_rel
              - cmake ..
          script: make

        - env: test="x64 5.0 (CMake clang)"
          os: linux
          dist: trusty
          compiler: clang
          before_script:
              - mkdir clang_rel && cd clang_rel
              - cmake ..
          script: make

        - env: test="x64 5.0 (CMake clang - Ninja) Debug"
          os: linux
          dist: trusty
          compiler: clang
          before_script:
              - mkdir clang_ninja_dbg && cd clang_ninja_dbg
              - cmake .. -GNinja -DCMAKE_BUILD_TYPE=Debug
          script: ninja

# ppc64le

        - env: test="ppc64le 4.8.4 (make)"
          os: linux
          dist: trusty
          compiler: gcc
          script: make
          arch: ppc64le

        - env: test="ppc64le 4.8.4 (autotools)"
          os: linux
          dist: trusty
          compiler: gcc
          script: ./autogen.sh && ./configure CFLAGS="-Werror -Wno-unused-result" && make distcheck
          arch: ppc64le

        - env: test="ppc64le 5.0 (autotools)"
          os: linux
          dist: trusty
          compiler: clang
          script: ./autogen.sh && ./configure CFLAGS="-Werror -Wno-unused-result" && make distcheck
          arch: ppc64le

        - env: test="ppc64le 4.8.4 (CMake gcc)"
          os: linux
          dist: trusty
          compiler: gcc
          before_script:
              - mkdir gcc_rel && cd gcc_rel
              - cmake ..
          script: make
          arch: ppc64le

        - env: test="ppc64le 5.0 (CMake clang)"
          os: linux
          dist: trusty
          compiler: clang
          before_script:
              - mkdir clang_rel && cd clang_rel
              - cmake ..
          script: make
          arch: ppc64le

        - env: test="ppc64le 5.0 (CMake clang - Ninja) Debug"
          os: linux
          dist: trusty
          compiler: clang
          before_script:
              - mkdir clang_ninja_dbg && cd clang_ninja_dbg
              - cmake .. -GNinja -DCMAKE_BUILD_TYPE=Debug
          script: ninja
          arch: ppc64le

# Android

        - env: test="Android NDK (CMake)"
          os: linux
          language: android
          android:
              components:
                  - build-tools-25.0.2
          install:
              - echo y | sdkmanager "ndk-bundle"
              - echo y | sdkmanager "cmake;3.6.4111459"
          before_script:
              - export ANDROID_NDK_HOME=$ANDROID_HOME/ndk-bundle
              - export ANDROID_CMAKE=$ANDROID_HOME/cmake/3.6.4111459/bin/cmake
              - export ANDROID_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake
          script:
              - pushd . && mkdir android15_armeabiv7a_rel && cd android15_armeabiv7a_rel
              - $ANDROID_CMAKE -DANDROID_PLATFORM=android-15 -DANDROID_ABI=armeabi-v7a -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=$ANDROID_TOOLCHAIN_FILE ..
              - make && popd

              - pushd . && mkdir android15_x86_rel && cd android15_x86_rel
              - $ANDROID_CMAKE -DANDROID_PLATFORM=android-15 -DANDROID_ABI=x86 -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=$ANDROID_TOOLCHAIN_FILE ..
              - make && popd

              - pushd . && mkdir android21_arm64-v8a_rel && cd android21_arm64-v8a_rel
              - $ANDROID_CMAKE -DANDROID_PLATFORM=android-21 -DANDROID_ABI=arm64-v8a -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=$ANDROID_TOOLCHAIN_FILE ..
              - make && popd

              - pushd . && mkdir android21_x86_64_rel && cd android21_x86_64_rel
              - $ANDROID_CMAKE -DANDROID_PLATFORM=android-21 -DANDROID_ABI=x86_64 -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=$ANDROID_TOOLCHAIN_FILE ..
              - make && popd

              - pushd . && mkdir android15_armeabiv7a_dbg && cd android15_armeabiv7a_dbg
              - $ANDROID_CMAKE -DANDROID_PLATFORM=android-15 -DANDROID_ABI=armeabi-v7a -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE=$ANDROID_TOOLCHAIN_FILE ..
              - make && popd

              - pushd . && mkdir android15_x86_dbg && cd android15_x86_dbg
              - $ANDROID_CMAKE -DANDROID_PLATFORM=android-15 -DANDROID_ABI=x86 -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE=$ANDROID_TOOLCHAIN_FILE ..
              - make && popd

              - pushd . && mkdir android21_arm64-v8a_dbg && cd android21_arm64-v8a_dbg
              - $ANDROID_CMAKE -DANDROID_PLATFORM=android-21 -DANDROID_ABI=arm64-v8a -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE=$ANDROID_TOOLCHAIN_FILE ..
              - make && popd

              - pushd . && mkdir android21_x86_64_dbg && cd android21_x86_64_dbg
              - $ANDROID_CMAKE -DANDROID_PLATFORM=android-21 -DANDROID_ABI=x86_64 -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE=$ANDROID_TOOLCHAIN_FILE ..
              - make && popd

addons:
    apt:
        packages:
            - autoconf
            - automake
            - libtool
            - m4
            - cmake
            - ninja-build
        sources:
            - ubuntu-toolchain-r-test
